/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `GeometrySphere`;

DROP TABLE IF EXISTS `Geometry3dBox`;

DROP TABLE IF EXISTS `Geometry2dBox`;

DROP TABLE IF EXISTS `AreaInstance_gameObjects`;

DROP TABLE IF EXISTS `AreaInstance`;

DROP TABLE IF EXISTS `GameObject`;

DROP TABLE IF EXISTS `Area`;

DROP TABLE IF EXISTS `GameObjectSpawn`;

DROP TABLE IF EXISTS `GameObjectTemplate`;

DROP TABLE IF EXISTS `GeometryObject`;

DROP TABLE IF EXISTS `StatSheet`;

DROP TABLE IF EXISTS `Account`;

CREATE TABLE `Account` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `username_i`
  ON `Account` (`username`);

CREATE TABLE `StatSheet` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `health` INT NOT NULL,
  `mana` INT NOT NULL,
  `moveSpeed` FLOAT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `GeometryObject` (
  `description` TEXT NOT NULL,
  `xDistance` FLOAT NOT NULL,
  `yDistance` FLOAT NOT NULL,
  `zDistance` FLOAT NOT NULL,
  `xAngle` FLOAT NOT NULL,
  `yAngle` FLOAT NOT NULL,
  `zAngle` FLOAT NOT NULL,
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(255) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `GameObjectTemplate` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `baseLevel` INT NOT NULL,
  `name` TEXT NOT NULL,
  `baseStats` BIGINT UNSIGNED NULL,
  `geometry` BIGINT UNSIGNED NULL
  /*
  CONSTRAINT `GameObjectTemplate_baseStats_fk`
    FOREIGN KEY (`baseStats`)
    REFERENCES `StatSheet` (`id`)
  */
  /*
  CONSTRAINT `GameObjectTemplate_geometry_fk`
    FOREIGN KEY (`geometry`)
    REFERENCES `GeometryObject` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `GameObjectSpawn` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `goTemplate` BIGINT UNSIGNED NULL,
  `xPos` FLOAT NOT NULL,
  `yPos` FLOAT NOT NULL,
  `zPos` FLOAT NOT NULL,
  `xAngle` FLOAT NOT NULL,
  `yAngle` FLOAT NOT NULL,
  `zAngle` FLOAT NOT NULL,
  `area` BIGINT UNSIGNED NULL
  /*
  CONSTRAINT `GameObjectSpawn_goTemplate_fk`
    FOREIGN KEY (`goTemplate`)
    REFERENCES `GameObjectTemplate` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `Area` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `instanceRequired` TINYINT(1) NOT NULL,
  `name` VARCHAR(255) NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `name_i`
  ON `Area` (`name`);

CREATE TABLE `GameObject` (
  `uuid` VARCHAR(255) NOT NULL PRIMARY KEY,
  `typeid` VARCHAR(255) NOT NULL,
  `level` INT NOT NULL,
  `name` TEXT NOT NULL,
  `stats` BIGINT UNSIGNED NULL,
  `goTemplate` BIGINT UNSIGNED NULL,
  `xPos` FLOAT NOT NULL,
  `yPos` FLOAT NOT NULL,
  `zPos` FLOAT NOT NULL,
  `xAngle` FLOAT NOT NULL,
  `yAngle` FLOAT NOT NULL,
  `zAngle` FLOAT NOT NULL
  /*
  CONSTRAINT `GameObject_stats_fk`
    FOREIGN KEY (`stats`)
    REFERENCES `StatSheet` (`id`)
  */
  /*
  CONSTRAINT `GameObject_goTemplate_fk`
    FOREIGN KEY (`goTemplate`)
    REFERENCES `GameObjectTemplate` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `AreaInstance` (
  `uuid` VARCHAR(255) NOT NULL PRIMARY KEY,
  `areaTemplate` BIGINT UNSIGNED NULL
  /*
  CONSTRAINT `AreaInstance_areaTemplate_fk`
    FOREIGN KEY (`areaTemplate`)
    REFERENCES `Area` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `AreaInstance_gameObjects` (
  `object_id` VARCHAR(255) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` VARCHAR(255) NULL,
  CONSTRAINT `AreaInstance_gameObjects_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `AreaInstance` (`uuid`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `AreaInstance_gameObjects_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `GameObject` (`uuid`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `AreaInstance_gameObjects` (`object_id`);

CREATE INDEX `index_i`
  ON `AreaInstance_gameObjects` (`index`);

CREATE TABLE `Geometry2dBox` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `xHalfExtend` FLOAT NOT NULL,
  `yHalfExtend` FLOAT NOT NULL,
  CONSTRAINT `Geometry2dBox_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `GeometryObject` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `Geometry3dBox` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `xHalfExtend` FLOAT NOT NULL,
  `yHalfExtend` FLOAT NOT NULL,
  `zHalfExtend` FLOAT NOT NULL,
  CONSTRAINT `Geometry3dBox_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `GeometryObject` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `GeometrySphere` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `radius` FLOAT NOT NULL,
  CONSTRAINT `GeometrySphere_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `GeometryObject` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

/*
ALTER TABLE `GameObjectSpawn`
  ADD CONSTRAINT `GameObjectSpawn_area_fk`
    FOREIGN KEY (`area`)
    REFERENCES `Area` (`id`)
*/

